### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by hdgarrood** [joneshf/purescript-node-child-process#2]
I would like to extract the code that deals with Node's `child_process` module from Pulp (which I recently ported to PureScript) into a separate library, and so this is the obvious candidate, but I don't think it's completely suitable as it currently is. How would you feel about the following:
- the `env` option in a `SpawnOptions` record might be better typed as `StrMap String`, because currently, each property could be any type, but they should only be `String`, I think.
- Also, it would be useful to make the `env` option `Nullable`, as the Node API allows you to pass `null` to inherit the parent's environment.
- Using a record type for `ChildProcess` is perhaps a bit unsafe, as we probably shouldn't allow updating of its fields. How about having a newtype without exporting the constructor, and then export functions to access those fields?
- `gid`, `uid`, and `pid` should probably be `Int`, not `Number`.
- Reading mutable state of a child process, eg `connected`, should probably require `Eff`.
- Do we gain from having a separate effect for each of stderr, stdin, stdout? How about just using `Spawn` for these too?
- Using `Array String` for the `stdio` option is a little limiting, as the [Node API](https://nodejs.org/api/child_process.html#child_process_options_stdio) allows you to pass other things instead of strings too, like streams or file descriptors. Also, in the case where you are passing a string, there are a specific set of valid values. We could just use `Foreign` here, or try to define a sum type, like I did [in Pulp](https://github.com/bodil/pulp/blob/4183431cb23e4e42e7156d797175dc24a64594c9/src/Pulp/System/ChildProcess.purs#L48-L64).

I would very happily send a PR with these things, if you agree. Also it might be nice to put this under `purescript-node` and/or publish it to Bower? If maintenance burden is an issue I'd happily take some of that on.

**Comment by joneshf** [comment]
I think all of these sound good with the exception of `Nullable` and the effects. I'm not familiar with `Nullable`, but assume it's good based on your suggestion.

> Do we gain from having a separate effect for each of stderr, stdin, stdout? How about just using Spawn for these too?

I can't remember exactly what use case I had in mind for this originally. I think it was something like users down the line could know up front if they were dealing with stdout vs stderr, and do things appropriate. But, I'll defer the judgement to you.

PR's are great if you feel up to it! Otherwise, I'm good implementing the changes.

I think it's already on bower: http://bower.io/search/?q=purescript-node-child-process Can you not install it?

I'm fine with transferring it over to `purescript-node` as well if that seems the better route.

**Comment by hdgarrood** [comment]
Cool, ok, I will send a PR soon.

Silly me: I assumed it was not on Bower because it isn't on Pursuit. I should have said: it would be nice to publish this to Pursuit. I can take care of that too.

**Comment by hdgarrood** [comment]
While I'm at it, how do you feel about pulp?
